src/app/index.config.coffee
Impac Widget without data, create a link to /apps that cant' be resolved
for a dedfault enterprise project
=> fix MNOE-52

src/app/components/mno-impersonation-bar/mno-impersonation-bar.directive.coffee
Changed the sentence "impersonating as" by "logged in as" when an admin logged in as a user.
=> [MNOE-87] - Changed the sentence "impersonating as" by "logged in as"

src/app/views/impac/impac.controller.coffee
Fixes widget loading issues when changing route from sidebar, and
when changing organization.
@alexnoox @cesar-tonnoir please review
=> [IMPAC-308][WES-29] Fix impac widget loading issues

src/app/views/layout.controller.coffee
=> [MNOE-122] Current user available in layout scope

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html
Changing the pricing.currency settings allow to select the default displayed currency in app prices.
=> Add possibility to select marketplace currency

src/app/index.config.coffee, src/app/views/layout.html, src/app/views/layout.less
=> Fix the dock center positioning

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.html, src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less, src/app/components/dashboard-menu/dashboard-menu.html
Change logout button to be inside Company select box(top right).
@alexnoox @x4d3
=> [MNOE-103] Change logout button

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.html, src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less, src/app/stylesheets/theme.less, src/app/stylesheets/variables.less, src/locales/en.locale.json
Changed the style of the user menu following the design of the maestrano (legacy) user menu.
Added a couple of minor changes.
=> [MNOE-141] Improve user menu

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less
I realised that I did not take into account the responsivity.
This should fix it.
=> Added responsivity to the company selectbox

src/app/index.config.coffee
=> Update impac-angular routes config for kpis & alerting

src/app/components/mnoe-api/app-instances.svc.coffee, src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html, src/app/views/marketplace/marketplace-app.less, src/locales/en.locale.json, src/locales/id.locale.json, src/locales/zh.locale.json
See https://github.com/maestrano/maestrano-hub/pull/153
=> [MNOE-165] Does not permit to install a second app if the app is not multi_instantiable

src/app/stylesheets/custom/accordion.less, src/app/stylesheets/custom/responsive-tables.less, src/app/stylesheets/custom/xeditable.less, src/app/stylesheets/variables.less, src/app/views/company/members/modals/invite-modal.html, src/app/views/company/members/organization-members.html, src/app/views/company/settings/organization-settings.html, src/app/views/company/team-list/modals/member-add-modal.html, src/app/views/company/team-list/team-list.html, src/app/views/company/teams/organization-teams.html, src/app/views/company/teams/organization-teams.less
- Company > Teams: Polish renaming and display
- Refactor tables action buttons
- Fix accordions border radius
- Better buttons semantic
=> Button semantic & Team section polishing

src/app/views/impac/impac.controller.coffee, src/app/views/impac/impac.html
=> Fix impac loader display

bower.json
@ouranos @x4d3 @hedudelgado FYI
=> Bumping resolutions versions

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html
App page was broken if the user had an app that was no longer available
on the marketplace.
Also refactored the code.
=> [MNOE-217] Fix app page

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/modals/choose-orga-modal.coffee
=> [MNOE-170] Redirect after adding an app

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less, src/app/components/mnoe-api/organizations.svc.coffee, src/app/components/theme-editor/theme-editor.html, src/app/stylesheets/variables.less, src/app/views/apps/modals/app-deletion-modal.html, src/app/views/apps/modals/app-settings-modal.html, src/app/views/company/settings/organization-settings.html, src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html, src/app/views/marketplace/modals/choose-orga-modal.coffee, src/app/views/marketplace/modals/choose-orga-modal.html, src/locales/en.locale.json
=> Fixes app provisionning

src/app/components/dashboard-apps-dock/dashboard-apps-dock.html, src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.html, src/app/components/dashboard-menu/dashboard-menu.html
Elements surrounding impac-angular must be print-hidden.
@alexnoox please review & merge
=> [impac-383] impac dhb printing display fixes

src/app/views/marketplace/marketplace-app.controller.coffee
=> Add missing service injection

src/app/components/mnoe-api/teams.svc.coffee, src/app/views/company/company.controller.coffee, src/app/views/company/members/organization-members.directive.coffee, src/app/views/company/team-list/team-list.directive.coffee, src/app/views/company/teams/organization-teams.directive.coffee
=> [MNOE-225] Fix teams multiple calls

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.coffee, src/app/components/dashboard-menu/dashboard-menu.html, src/app/components/mnoe-api/organizations.svc.coffee
@ouranos Some bugs were still experienced while creating a company. It was related to asynchronism and backend response time, resulting in an incoherent state. I solved it by using a better promise management.
=> [MNOE-215] Fix and clean company creation

src/app/components/mnoe-api/organizations.svc.coffee, src/app/views/company/members/organization-members.directive.coffee
Removed the possibility for Super User to modify their role if they are the only super user left.
=> [MNO-324] - Change SuperAdmin role - frontend

bower.json
=> Bump angular version

src/app/views/account/account.html
@BrunoChauvet Please review and merge
=> [MNO-287] Fix developer section style

src/app/views/marketplace/marketplace-app.controller.coffee, src/locales/en.locale.json
- `or` is not working in when condition
- Fix locale name
@BrunoChauvet Please review
=> [MNOE-241] Fix launch notification when adding an app

src/app/views/marketplace/marketplace-app.controller.coffee
=> [MNOE-241] office-365 exception

src/app/impac.config.coffee
=> [IMPAC-408] Access pusher_key from IMPAC_CONFIG

bower.json
Bump angular version.
@xaun should solve issue #MNOE-263
=> Develop angular 1.6.0

src/app/stylesheets/custom/accordion.less, src/app/stylesheets/custom/responsive-tables.less, src/app/stylesheets/theme.less, src/app/stylesheets/variables.less, src/app/views/account/account.html, src/app/views/company/teams/organization-teams.less, src/app/views/marketplace/marketplace.less
Hi @x4d3 & @hedudelgado,
Please review this PR. I worked on this with @CamilleCrespeau during the Peer Programming session.
This PR is the continuation of this PR: https://github.com/maestrano/mno-enterprise-angular/pull/92 by @adamaziz15.
As you can see I added some less variables so be careful if you need to create or especially update a project.
Cheers
=> [MNOE-105] New default colors

src/app/views/marketplace/marketplace-app.less
=> Move text and button to the left

src/app/views/marketplace/modals/create-review-modal.controller.coffee, src/app/views/marketplace/modals/create-review-modal.html
=> Limit number of characters in comments

bower.json, src/app/views/company/members/organization-members.directive.coffee, src/app/views/company/team-list/team-list.directive.coffee, src/app/views/company/teams/organization-teams.directive.coffee
@ouranos Please review
FYI @cesar-tonnoir @xaun @hedudelgado @x4d3 
Guys,
This PR is the counterpart of https://github.com/maestrano/impac-angular/pull/280. It fixes the build and upgrade versions.
=> [MNOE-268] Upgrade angular & ui-bootstrap

src/app/views/marketplace/marketplace-app.html
@alexnoox @ouranos This should fix the issue of being able to click the button multiple times while it is loading. This happened due to the fact that in angular the ng-disabled directive only truly works on button elements. Since the button is an <a> element it doesn't disable the ng-click directive.
=> [MNOE-252] Fix (Start Now) Button

src/app/components/dashboard-menu/dashboard-menu.less, src/app/stylesheets/theme.less, src/app/stylesheets/variables.less, src/app/views/marketplace/marketplace-app.less
@ouranos While updating the demo, I stumbled upon variables that where misused, and it leaded to unused variables to remove.
I also added the `@login-box-oauth-*` variables as the ones used at the moment for the static pages are in `mno-enterprise/frontend/app/assets/stylesheets/mno_enterprise/variables.less`, but this will need to change.
Please review and merge.
=> Fixing variables using bg for text, remove useless variables

src/app/views/marketplace/marketplace-app.html
=> Fix carousel in marketplace app

src/app/impac.config.coffee
@alexnoox please review.. Is the the appropriate branch to be requesting to merge into? Note this change is only compatible with impac-angular >= v1.4.6.
=> Refactor impac routes config to use defaults

src/app/views/company/team-list/modals/member-add-modal.html
@alexnoox can you have a quick look on this one?
Cheers :turkey:
=> [MNOE-299] Remove unused add button on team full

src/app/impac.config.coffee
@cesar-tonnoir Please review the general impac config? 
@ouranos FYI
=> [MNOE-289][MNOE-292] Fix 'Are you missing an app' link

src/app/views/marketplace/marketplace-app.controller.coffee
=> [MNO-536] Fix behaviour in comments and answers

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less, src/app/stylesheets/variables.less, src/app/views/apps/modals/app-deletion-modal.html, src/app/views/apps/modals/app-deletion-modal.less, src/app/views/apps/modals/app-settings-modal.html, src/app/views/apps/modals/app-settings-modal.less
@alexnoox can your review this please?
=> [MNOE-105] Final changes of theme colors

src/app/index.config.coffee
@alexnoox can you review this please?
=> [MNOE-320] App Comparison - Multiple notification displayed when more than 4 apps

src/app/views/marketplace/marketplace-app.html
@alexnoox can you review this please? :)
=> [MNOE-344] - Enable answer edit

src/app/filters/mno-filter-questions.coffee, src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html
@alexnoox can you review this please? :)
=> [MNOE-339] - Fix search issue on questions

src/app/components/mno-app-install-btn/mno-app-install-btn.coffee, src/app/components/mno-app-install-btn/mno-app-install-btn.html, src/app/views/marketplace/modals/choose-orga-modal.coffee, src/locales/en.locale.json
=> [MNOE-357] - Error message displayed incorrect

src/app/views/marketplace/marketplace-app.controller.coffee
=> [MNOE-347] - Allow mutiple comment edit

src/app/components/mno-app-install-btn/mno-app-install-btn.coffee, src/app/components/mno-app-install-btn/mno-app-install-btn.html, src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html, src/app/views/marketplace/marketplace-compare.html
=> Fix app install button component behaviour

src/app/components/mno-impersonation-bar/mno-impersonation-bar.less
=> Fix text on impersonating feature no readable

src/app/components/mno-app-install-btn/mno-app-install-btn.html, src/locales/en.locale.json
=> [MNOE-403] Fix tooltip locale

src/app/components/mno-audit-events-list/mno-audit-events-list.coffee, src/app/stylesheets/theme.less, src/app/stylesheets/variables.less, src/app/views/layout.less
@ouranos You may have forgot a callback ;)
I also fixed the responsiveness of the layout.
=> Fix auditlog and layout

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.html, src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.less, src/app/stylesheets/variables.less
=> Company selectbox: Add more variables

src/app/components/dashboard-apps-dock/dashboard-apps-dock.html
=> [MNOE-404] Fix dock behaviour in ipad and phone

src/app/components/mno-without-organisation/mno-without-organisation.coffee, src/app/components/mno-without-organisation/mno-without-organisation.html, src/app/components/mno-without-organisation/mno-without-organisation.less
=> [MNOE-401] No organisation component

src/locales/en.locale.json
=> Fix no organisation locale

src/app/views/layout.html
=> [MNOE-484] Fix locale key displayed on loading screen

src/app/components/mnoe-api/organizations.svc.coffee, src/app/views/apps/dashboard-apps-list.controller.coffee, src/app/views/apps/dashboard-apps-list.html
@ouranos and @alexnoox for review
=> [MNOE-464] - Remove connect button for non admin users

src/app/components/mno-app-onboarding-btn/mno-app-onboarding-btn.coffee, src/app/components/mno-app-onboarding-btn/mno-app-onboarding-btn.html, src/locales/en.locale.json
=> Onboarding step 3: Add-ons management

src/app/views/company/teams/organization-teams.directive.coffee
=> [MNOE-491] Fix teams

src/app/index.run.coffee, src/app/views/layout.html, src/app/views/onboarding/layout.html, src/index.html
=> [DEVPL-74] Display dashboard loader for any routing case

src/app/components/mnoe-api/app-instances.svc.coffee, src/app/index.run.coffee
=> [MNOE-407] Onboarding: fix app instances loading

src/app/components/mnoe-api/organizations.svc.coffee, src/app/index.constants.coffee
=> [MNOE-407] Onboarding: fix connec link & organisation first call

src/app/components/mnoe-api/organizations.svc.coffee, src/app/index.route.coffee, src/app/index.run.coffee
=> [MNOE-407] Onboarding: fix organisation initialisation

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.coffee, src/app/components/dashboard-menu/dashboard-menu.controller.coffee, src/app/components/impac-config/impac-config.svc.js.coffee, src/app/views/company/members/organization-members.directive.coffee, src/app/views/impac/impac.controller.coffee, src/app/views/layout.controller.coffee, src/app/views/marketplace/marketplace-app.controller.coffee
Due to migration to v2 - All the ids are now string in mnoe
=> Remove unused parseInt

gulp_tasks/styles.js, src/app/index.less
=> Default variables: change less files priority & fix layout

src/app/index.less
=> [MNOE - 518] - Fix pop-up app confirmation

src/app/components/theme-editor/theme-editor.directive.coffee, src/app/components/theme-editor/theme-editor.html, src/app/components/theme-editor/theme-editor.less
=> [MNOE-452] Theme previewer polish

src/app/components/theme-editor/theme-editor.html
- Add a button to get back to the admin panel
- Move "Logo" before advanced
- Add warning on advanced section
=> [MNOE-452] Polish theme previewer

src/app/views/marketplace/marketplace-app.controller.coffee
@ouranos @BrunoChauvet Please review
=> [MNOE-535] Provisioning: Remove product call on marketplace app

src/app/components/mnoe-api/teams.svc.coffee, src/app/views/company/team-list/team-list.directive.coffee, src/app/views/company/teams/organization-teams.directive.coffee
=> [MNOE-495] Fix adding members in team not working as expected

src/app/components/theme-editor/theme-editor.html
The upload process only supports png file for now.
This will be reworked when implementing support for arbitrary assets.
=> [MNOE-452] Theme previewer - Restrict logo type

src/app/components/mno-app-onboarding-btn/mno-app-onboarding-btn.html, src/app/views/onboarding/step2.html, src/app/views/onboarding/step2.less
Reverts maestrano/mno-enterprise-angular#233
=> Revert "[MNOE-501] UI improvement on-boarding"

src/app/components/dashboard-apps-dock/dashboard-apps-dock.coffee
=> Fix typo in variable name

src/app/views/marketplace/marketplace-app.controller.coffee
Fix top counters when creating the first review or question
=> [MNOE-474] Fix review UI

src/app/views/marketplace/marketplace-app.html
@alexnoox 
Edit: 
FYI the JIRA description:
> Issue 2: When a comment is edited by admin panel, "edited by user" is appearing instead of "platform moderator"
> Issue 3 : When answer is posted by "admin" it is appearing as "Posted by user"
=> [MNOE-558] Update handling of admin_role for reviews/questions frontend

src/app/components/mnoe-tasks/mnoe-tasks.coffee
=> Tasks fixes

src/app/index.less, src/index.html
@alexnoox @ouranos Added translate-cloak directive to fix FOUC error as we had done in [MNOE-555]
=> [MNOE-555] Use translate cloak to fix FOUC error

src/app/components/mnoe-tasks/mnoe-tasks.coffee
@alexnoox please review & merge
=> Fix due tasks filter to exclude done tasks

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/provisioning/details.controller.coffee, src/app/views/provisioning/order.controller.coffee
@fgourichon @ouranos @alachaum FYI
=> [MNOE-476] Markup: Fix services dependencies

src/app/views/marketplace/marketplace-compare.controller.coffee, src/locales/en.locale.json
@ouranos @alexnoox This should take care of the Nan displayed for some of the average ratings on the compare page. Please review. :)
=> [MNOE-587][Bug] Nan average rating

src/app/components/mnoe-api/marketplace.svc.coffee, src/app/views/marketplace/marketplace-product.controller.coffee
- Pass organization id on local product request
- Reload local products when users switch org
=> Fix markup display on local products

src/app/components/mnoe-api/current-user.svc.coffee
@ouranos @alexnoox I think this will make the redirects a bit cleaner. Now it doesn't go to the landing page at all if public pages are not enabled.
=> Public Pages - fix redirect logic

src/app/components/mnoe-api/current-user.svc.coffee, src/app/index.route.coffee
@alexnoox not sure if we can make this cleaner.
* This fix the bug with `!MnoeCurrentUser.get()` always being true.
* Also fix MnoeCurrentUser.get() not always returning a promise
=> Fix default route and MnoeUser svc

package.json
=> Add gulp-header to dependencies

src/app/components/dashboard-language-selectbox/dashboard-language-selectbox.coffee, src/app/components/mno-confirm/mno-confirm.html, src/app/components/mno-confirm/mno-confirm.svc.coffee, src/app/views/company/members/modals/invite-modal.html, src/app/views/company/members/organization-members.directive.coffee, src/locales/en.json
@alexnoox Applied comments from code review here: https://github.com/maestrano/mno-enterprise-angular/pull/309
Also continuing work on this ticket in this PR. 👍
=> [MNOE-597][Bug] Missing Conversion

bower.json
Handle date-time format in product json schemas.
See https://github.com/maestrano/mnoe-admin-panel/pull/108 for the admin panel side.
=> [MNOE-594] Add datepicker on product forms

src/app/views/apps/modals/app-settings-modal.html, src/locales/en.json
@alexnoox Updated locales. Please review. :)
=> [Bug] missing locale

src/app/index.less
@alexnoox This styling update should handle some UI bugs on IE11. ng-hide/ng-show has a lag on IE11 causing both elements to show simultaneously for a moment. This fixes that issue on IE11 and has no effect on chrome. (checked both just in case) Please review. :)
=> [BUG] IE11 UI issues - widget refresh

src/app/index.less
@alexnoox Please review. Additional comments in JIRA.
=> Fix cloaking issue on IE11

bower.json, src/app/index.module.coffee, src/app/views/marketplace/marketplace-app.html
Displays the video instead of a image. Needs the other pull request on MNOE to receive correctly the description's html (was sanitized)
=> [DEVPL-157] Video player on an app's description

src/app/components/mnoe-config/mnoe-config.svc.coffee
https://github.com/maestrano/mno-enterprise/pull/507
=> [MNOE-656] Disable onboarding

bower.json
required by impac-angular custom branch => https://github.com/maestrano/impac-angular/tree/archive/legal-widgets
=> Overrides jquery-rss config

src/app/views/marketplace/marketplace-app.html, src/app/views/public/product/product.html, src/locales/en.json
Depends on https://github.com/maestrano/maestrano-hub/pull/748
=> [MNOE-685] display pricing type on marketplace

src/app/components/theme-editor/theme-editor.directive.coffee, src/app/components/theme-editor/theme-editor.html, src/app/components/theme-editor/theme-editor.svc.coffee
- Reset to default style
- Add toastr messages
- Confirmation on save
- Warning on exit (page change or close tab) if unsaved changes
=> [MNOE-695][MNOE-693] Theme previewer: reset to default & confirmation msg

src/app/components/dashboard-language-selectbox/dashboard-language-selectbox.coffee, src/app/components/mno-locale-config/mno-locale-config.svc.coffee
Make sure that the locale is available before setting it.
Fix bug when a locale/I18n is disabled and the locale doesn't revert to
the default locale.
=>  [MNOE-714] Check locales availability

src/app/views/marketplace/marketplace.controller.coffee, src/app/views/marketplace/marketplace.html
@alexnoox I added the calculation in the controller, but I would save this line of code and add it in the view. What do you think?
=> [MNOE-345] Fix display categories filter when only one

src/app/components/mnoe-api/provisioning.svc.coffee, src/app/views/provisioning/subscription.controller.coffee, src/app/views/provisioning/subscription.html, src/locales/en.json
=> [MNOE-750] Display subscription events on info page

src/app/components/theme-editor/theme-editor.less
See comments https://maestrano.atlassian.net/browse/MNOE-718?filter=-1
@ouranos
=> [MNOE-718] Colorpicker z-index

src/app/components/theme-editor/theme-editor.directive.coffee
@ouranos 
syntax error fixed
https://maestrano.atlassian.net/browse/MNOE-785
=> [MNOE-785] Theme previewer import

src/app/components/theme-editor/theme-editor.directive.coffee
@ouranos 
html download attribute not supported in ie11
https://maestrano.atlassian.net/browse/MNOE-786
=> [MNOE-786] Theme previewer export

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html
=> [MNOE-766] Fix review and question count not sync

src/app/components/dashboard-menu/dashboard-menu.controller.coffee, src/app/components/dashboard-menu/dashboard-menu.html, src/app/components/mnoe-config/mnoe-config.svc.coffee, src/app/views/impac/impac.controller.coffee
@ouranos @alexnoox please review
=> Update frontend to allow disabling of impac dashboard via feature flags

src/app/views/marketplace/marketplace.html
=> [MNOE-765] Fix displaying compare button when 0 or 1 app

bower.json
Unable to add reviewer.
Issues appear to be fixed with es6-shim
@ouranos @alexnoox
=> [MNOE-810]  IE-11 Dashboard Issues

src/app/views/provisioning/order.controller.coffee, src/app/views/provisioning/order.html
@ouranos 
unable to add reviewers
=> [MNOE-770] Mandatory license field for license-based subscriptions

src/app/index.run.coffee, src/index.html, src/locales/en.json
=> [MNOE-793] Change title to Customr View and i18n it

src/app/views/provisioning/subscription-status-info-modal/subscription-status-info.controller.coffee, src/app/views/provisioning/subscription-status-info-modal/subscription-status-info.html, src/app/views/provisioning/subscription.controller.coffee, src/app/views/provisioning/subscription.html, src/app/views/provisioning/subscriptions.html, src/locales/en.json
Tooltip to explain subscription 'Aborted' status was not displayed in details page in dashboard.
Also resized columns in subscriptions list
=> [MNOE-767] - Display aborted tooltip in dashboard

src/app/components/dashboard-menu/dashboard-menu.html
=> [MNOE-894] Logo redirects to the dashboard

src/app/views/marketplace/marketplace-app.controller.coffee, src/app/views/marketplace/marketplace-app.html, src/app/views/provisioning/order.controller.coffee, src/app/views/provisioning/order.html, src/app/views/provisioning/subscription.controller.coffee, src/app/views/provisioning/subscription.html, src/app/views/public/product/product.controller.coffee, src/app/views/public/product/product.html
Constant is not accessible in the view.
Refactor to use a helper
=> [MNOE-934] Fix pricing display

src/app/components/mno-app-features/mno-app-features.coffee
@cesar-tonnoir 
Dependent on:
https://github.com/maestrano/mno-enterprise/pull/660
https://github.com/maestrano/maestrano-hub/pull/910
=> [APPINT-1161] Add sso_enabled

src/app/components/mno-apps/mno-app.coffee, src/app/components/mno-apps/mno-app.html, src/app/services/provisioning-helper/provisioning-helper.coffee, src/app/views/provisioning/order.controller.coffee, src/app/views/provisioning/order.html, src/app/views/provisioning/subscription.controller.coffee, src/app/views/provisioning/subscription.html
In order to stay consistent with MNOE-Admin Panel: https://github.com/maestrano/mnoe-admin-panel/pull/236/files
=> [MNOE-1008] Refactor vm.pricedPlan

src/app/components/mno-local-products/mno-local-product.html, src/locales/en.json
Unable to assign reviewer @ouranos 
Reliant on: https://github.com/maestrano/mno-enterprise/pull/680 for testing
=> [MNOE-962] Add pricing plan type for reseller products

src/app/components/mno-app-install-btn/mno-app-install-btn.coffee, src/app/components/mno-app-install-btn/mno-app-install-btn.html, src/app/components/mnoe-api/provisioning.svc.coffee, src/app/index.route.coffee, src/app/views/provisioning/confirm.controller.coffee, src/app/views/provisioning/confirm.html, src/app/views/provisioning/details.controller.coffee, src/app/views/provisioning/order.controller.coffee, src/app/views/provisioning/subscriptions.controller.coffee, src/app/views/provisioning/summary.controller.coffee, src/app/views/provisioning/summary.html
@ouranos @BrunoChauvet 
This replaces: https://github.com/maestrano/mno-enterprise-angular/pull/453/files. Identical work done on admin panel: https://github.com/maestrano/mnoe-admin-panel/pull/238
=> [MNOE-971][MNOE-1018] Keep data when editing order/Fix Refresh bug

src/app/components/mnoe-api/teams.svc.coffee, src/app/views/company/team-list/modals/member-add-modal.controller.coffee, src/app/views/company/team-list/modals/member-add-modal.html, src/app/views/company/team-list/modals/member-removal-modal.controller.coffee, src/app/views/company/team-list/modals/member-removal-modal.html, src/app/views/company/team-list/team-list.directive.coffee, src/app/views/company/team-list/team-list.html
@ouranos Tried to clean up a bit
=> [MNOE-1038] Team Management - Issue with adding an removing users

src/app/components/mnoe-api/teams.svc.coffee, src/app/views/company/team-list/team-list.directive.coffee
this happens when adding app to the team, or change team name
=> [MNOE-1036] Error occurs when adding member to team

src/app/components/mno-app-install-btn/mno-app-install-btn.coffee, src/app/components/mno-local-products/mno-local-product.coffee, src/app/components/mno-local-products/mno-local-product.html
Fixed issues with provisioning of local and regular products for different types of users
=> [MNOE-1148] Fixed issues with provisioning of products for members

src/app/components/mno-apps/mno-app.coffee, src/app/components/mno-apps/mno-app.html, src/app/services/app-management-helper/app-management-helper.coffee, src/app/services/provisioning-helper/provisioning-helper.coffee
- Add guarding to prevent error when setting sync status in apps
management page
- Do not display 'not available in your currency' message when product
skips pricing selection
=> [MNOE-1220][MNOE-1221] Product bugs

src/app/components/mno-apps/mno-app-listing.coffee, src/app/components/mno-apps/mno-app-listing.html
Created custom filter to only search certain fields
Moved filter to a ng-change method to improve performance
=> [MNOE-1007] Improve Marketplace Filtering

src/app/components/mnoe-api/marketplace.svc.coffee
Update marketplace service to set organization_id param when fetching a
single product.
=> [MNOE-1203] Product Markups

src/app/views/provisioning/order.html, src/app/views/provisioning/subscriptions.html
=> [MNOE-1149] add tooltips and improve bootstrap for subscription tables

src/app/components/mno-local-products/mno-local-product.coffee, src/app/components/mno-local-products/mno-local-product.html
Updated local products provision button on the basis of currency
=> [MNOE-1263] [OPAL-497] Updated local products provision button

src/app/components/mno-local-products/mno-local-product.coffee
Allow Local Product ordering when currency selection is enabled.
@RidaAhmad @adamaziz15 @iseessel
This was broken by #532. 
`vm.product.pricing_plans?[0].default?[0]` was always false as this is the structure for App not Product.
I took the opportunity to refactor a little bit.
=> [OPALSUP-113] Fix currency selection for local product

src/app/views/apps-management/app-management/app-management.controller.coffee, src/app/views/apps-management/apps-management.controller.coffee
- Update apps management controllers to find subscriptions using
product_instance_id
=> [MNOE-1297] Subs Management
