src/app/views/apps/modals/app-settings-modal.coffee
@alexnoox @ouranos @x4d3 
This change has been done to solve the problem that the following PR will cause.
https://github.com/maestrano/mno-enterprise/pull/69
=> Fix addOn to add_on issue

src/app/index.run.coffee
Display flash messages from the backend in a toastr.
They're passed this way:
`?flash={"msg":"An error message.","type":"error"}`
=> [MNOE-113] Display backend flash messages

src/app/index.default-config.coffee, src/app/index.module.coffee
Avoid Unknown provider error when the frontend is newer than the
backend and using constants that are not defined in the backend config
file.
=> Config backward compatible with the mnoe backend

src/app/views/layout.less
@alexnoox 
@x4d3 
The variables gif loader and text loader are pointing at different places, one points at theme.less and the other point at variables.less, therefore when I change the colour of the loader, the text remains with the same colour, it looks VERY ugly and I need to be overwrite the text. This way both will point at the same variable.less, saving time and bugs.
I hope this is ok.
Thanks.
=> Change color variable text loader to match loader color

src/app/components/dashboard-menu/dashboard-menu.controller.coffee, src/app/views/impac/impac.controller.coffee, src/app/views/login-router/login-router.coffee
Prevent unnecessary $state redirect to #/login to authenticate
user role by using MnoeOrganizations.role methods directly in the
dashboardMenu directive controller.
@alexnoox please review
=> Fix impac dashboard double loading

bower.json
Reverts maestrano/mno-enterprise-angular#102
Angular 1.6 is a major version that needs a round of testing. Also the impac! team will need to make sure they are not using anything deprecated in this version.
FYI @xaun @cesar-tonnoir
=> Revert "Develop angular 1.6.0"

src/app/index.run.coffee
@alexnoox I noticed a token error in the console anytime there is an in-app alert. This was due to the ng-bind-html directive having braces => {} around it.
=> Fix angular token error

src/app/views/marketplace/marketplace-app.html
Regardless what the documentation says (https://angular-ui.github.io/bootstrap/#/carousel)
```
Use a <uib-carousel> element with <uib-slide> elements inside it.
```
the code specifically restrict uib-carousel & uib-slide to be an attribute (https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.js#L289).
@ouranos FYI
=> uib-carousel & uib-slide cannot be an element

src/app/index.config.coffee
The logging of missing translations in production spams the console and makes the application lag => temporarily disabling it until a "developer mode" is available in mnoe-angular.
-- Tested on my local
=> Temporarily disable angular-translate logger

src/app/components/mnoe-api/audit-events.svc.coffee
Evaluate the OrganizationId at each call rather than once.
=> [MNOE-399] Dynamic base url for Audit Log

src/app/views/company/company.controller.coffee, src/app/views/company/company.html
@ouranos 
The "active" is a setting for uib-tabset, but not in the uib-tab, so I got rid of it.
The ng-if does not work properly together with uib-tab, as a result all the idexes where messed up.
I added new indexes on each tab as strings for readibility.
I use the index to set the default tab depending of the condition vm.isBillingShown.
=> [MNOE-437] Fix wrong default tab in organization

src/app/index.route.coffee
@ouranos Please review
If the onboarding is disabled, the page cannot load due to a missing dependency. This PR fix this error.
=> [MNOE-407] Fix error when onboarding is disabled

gulp/locales.js, gulp/server.js, gulp/styles.js
- Remove deprecated `util.isArray()`
@ouranos @cesar-tonnoir @xaun 
Tiny gulp task that runs before `gulp serve` to ensure locales are available in development
=> Add gulp task to ensure locales in development

gulp_tasks/styles.js
Using a `variables*` will preserve the order and still work when `variables-default.less` is not present (ie: when building from the project folder)
Test:
```js
var glob = require("glob")
glob("src/app/stylesheets/variables*.less", {}, function (er, files) {
console.log(files)
})
```
```
∫ node test.js 
[ 'src/app/stylesheets/variables-default.less',
'src/app/stylesheets/variables.less' ]
```
=> [MNOE-541] Fix build when variable-default not present

src/app/components/dashboard-apps-dock/dashboard-apps-dock.coffee, src/app/components/dashboard-apps-dock/dashboard-apps-dock.html
The dock must be display when the marketplace is disabled but there are
apps.
=> [MNOE-499] Fix regression in dock display

src/app/views/marketplace/marketplace-app.controller.coffee
@alexnoox This is regarding a bug where, when the first review is added to an app, the star rating towards the top of the page does not update unless the page is refreshed. I think this has something to do with averageRating being set to Null. I think for some reason it is messing with the average-star-rating component and it is not able to update properly (maybe related to the $watch function in average-star-rating) as this only happens when there are no reviews, and also happens if you delete all the reviews and add one again (all without refreshing).
=> Fix star ratings bug

src/app/components/mnoe-api/marketplace.svc.coffee
@alexnoox @ouranos The ratings still had a bug when clicking the back button and then opening the same app as the rating would not be updated in the marketplacePromise. Should be all good now. 👍  Please review.
=> Reset promise when app ratings are updated (Rating stars bug fix)

src/app/components/mnoe-api/app-instances.svc.coffee
Still return the cached results, but refresh them in the background
=> [MNOE-567] Refresh AppInstance cache asynchronously

bower.json, src/app/views/provisioning/details.controller.coffee
Summary of changes:
- Upgrade angular-schema-form to 1.0.0-alpha4
- Force multiples passes on JSON schemas to resolve $ref pointers
=> Handle $ref in product JSON schemas

src/app/components/mno-locale-config/mno-locale-config.svc.coffee
@alexnoox When no locale is set via the url or user, `setFallbackStack` is called. Since the function doesn't set a locale for angular Moment.js, the date on the subscription page is appearing in chinese. This should take care of the issue. Please review. :)
=> [MNOE-621][BUG] Update angular moment with fallback locale

bower.json, src/app/index.controller.coffee
@alexnoox This PR should take care of some issues on the change password page. The function comes from ES6 which is not supported by IE11 so this replaces the function in that case. Please review.
=> Update isInteger for IE11

package.json, src/app/components/theme-editor/theme-editor.directive.coffee, src/app/stylesheets/variables.less
Add wiredep-cli to the dependencies. Wiredep is used by the mno-enterprise tasks to resolve less dependencies.
Also fix some less variables issues. A few things to note:
- Less logo paths must be enclosed in double quotes
- We need to avoid putting comments in-line after variables
- It looks like '@elem-cozy-color' is not used anymore. What should be the default value for @input-bg?
@alexnoox need to discuss with you before merging.
=> Prepare for compilation speedup

bower.json, src/app/components/theme-editor/theme-editor.html, src/app/components/theme-editor/theme-editor.less, src/app/index.module.coffee
https://maestrano.atlassian.net/browse/MNOE-718
IE11 Bug fixes for theme-previewer:
IE11 does not support the color input type.  I have implemented a color picker that is compatible across browsers.
IE11 does not allow the use of css calculations with 3d transform, which was preventing the theme previewer panel from closing. I have changed the value from (100%-30px) to be 95%, leaving 5% of the panel visible.
=> [MNOE-718] Theme Previewer

bower.json, src/app/index.config.coffee, src/app/index.module.coffee, src/app/views/provisioning/subscription.controller.coffee, src/app/views/provisioning/subscription.html, src/app/views/provisioning/subscription.less, src/locales/en.json
Feature preview:
@alexnoox could you confirm that removing `json-formatter` and its configuration has no side effects? I haven't found pages where it was used previously.
=> [MNOE-750] Display SubscriptionEvent provisioning data

src/app/views/marketplace/marketplace-product.controller.coffee, src/app/views/provisioning/confirm.controller.coffee, src/app/views/provisioning/order.controller.coffee, src/app/views/provisioning/subscriptions.controller.coffee, src/app/views/provisioning/summary.controller.coffee
Point on new field organization.billing_currency rather than on the billing section, which is not available for all users (only super admins)
Depends on mnoe PR:
https://github.com/maestrano/mno-enterprise/pull/569
=> [MNOE-780] - Use organization billing_currency

src/app/components/mno-app-install-btn/mno-app-install-btn.html, src/app/components/mno-app-install-btn/mno-app-install-btn.less
@alexnoox @ouranos The tooltip works properly in ie11 now. On internet explorer, when using the ng-disabled directive, the browser prevents all tooltips from showing.
=> [MNOE-794] [BUG] Insufficient Privileges Tooltip not showing on IE11

CHANGELOG.md, bower.json, src/app/components/dashboard-menu/dashboard-menu.controller.coffee, src/app/components/dashboard-menu/dashboard-menu.html, src/app/components/impac-config/impac-config.svc.js.coffee, src/app/impac.config.coffee, src/app/views/apps/dashboard-apps-list.controller.coffee, src/app/views/impac/impac.controller.coffee, src/app/views/layout.controller.coffee
- Rework conditional display of Impac! and menu buttons based on ACL for user / selected organization
- Add `ImpacConfigSvc.configure` = ability to pass a function that customises the list of organizations before passing them to Impac!
**Note**: The ACL for a tenant should be modified via ActiveAdmin (tenant metadata) instead of using the `ImpacConfigSvc.configure` helper. The later is kept in the code as an improvement if some overrides are needed on the organizations passed to Impac!
=> Impac! permissions

src/app/views/apps/modals/app-connect-modal-myob.coffee, src/app/views/apps/modals/app-connect-modal-xero.coffee
@alexnoox The call to `MnoeAppInstances.oAuthConnectPath(app)` in the modals was happening before it was needed and was causing all of the app instances to be cleared from the `MnoeAppInstances` service. I refactored the modals to prevent the apps from disappearing from the dock pre-maturely.
=> [MNOE-626] Refactor modals to prevent clearing of app instances svc

src/app/components/mnoe-tasks/mnoe-tasks.coffee, src/app/views/messages/messages.controller.coffee
@ouranos @x4d3 @alexnoox Ready for review 👍
=> [MNOE-795] Refresh messages page when changing organizations

src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.coffee
- Company was fetched from MnoeCurrentUser, which relied on the cache from mno-enterprise. Therefore, the company name was not updated on refresh.
- MnoeOrganizations.selected is set right after MnoeOrganizations.selectedId is set.
Since the watch that triggers selectOrganization() is on MnoeOrganizations.selectedId, MnoeOrganizations.selected can be nil at this point, so we keep what we had as a fallback
=> [MNOE-561] Update company name on refresh

src/app/components/mno-apps/mno-app.coffee
- ~~When fetching apps/products, we do not get updated pricing details since we are showing cached versions of the apps against that organization.~~
- Allow Product pricings to be updated when organization is changed
=> [OPAL-305] Update Product pricings when organization is changed

src/app/views/provisioning/order.controller.coffee
Simple problem -- You would click a license based subscription which would ng-model to vm.subscription.max_licenses, when clicking away you wouldn't reset vm.subscription.max_licenses.
=> [OPAL-459] Fix Licenses not resetting bug

src/app/components/mno-app-install-btn/mno-app-install-btn.coffee, src/app/views/provisioning/summary.controller.coffee
Add guarding to summary controller to prevent error thrown when product
is set to skip price selection.
=> [OPAL-513] Locales displayed on "Validate"

src/app/components/mno-apps/mno-app-listing.coffee, src/app/components/mno-local-products/mno-local-product-listing.coffee, src/app/views/public/landing/landing.controller.coffee
The public marketplace view on the landing page now correctly
shows local products flagged as public, removes categories
where no public products are configured and on initial view
does no longer shows all products initially.
This change also fixes the category selection in the marketplace
which was not working because not all products have categories.
=> [OPALSUP-265] Fix public marketplace view

src/app/components/mno-apps/mno-app.coffee
The detailed product display component is designed to show
product information within the landing page where a user
is not logged and there is no selected organisation.
Fix the logic to support this use case by not relying on
a selected organisation.
=> [MNOE-1277] Product display allow undefined org

src/app/components/mnoe-config/mnoe-config.svc.coffee, src/app/views/company/settings/organization-settings.directive.coffee, src/app/views/company/settings/organization-settings.html, src/app/views/company/settings/organization-settings.less, src/locales/en.json
Add a new flag to control the ability to select an organization billing currency.
Removed the condition around 'Super Admin' as the directive is only shown for 'Super Admin'
New flag:
Tooltip when disabled:
=> [OPALSUP-281] Add billing currency flag

package.json
Update gulp dev dependency in package.json as gulp 4.0 is now available
directly from npm (git reference is no longer valid)
=> Update dev dependency
